shop/customers/routes.py
from flask import render_template, session, redirect, request, url_for, flash, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from shop import db, bcrypt
from shop.customers.forms import RegistrationForm, LoginForm, UpdateForm
from shop.customers.models import Customer
customers = Blueprint('customers', __name__)


@customers.route("/registration", methods=['GET', 'POST'])
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        customer = Customer(username=form.username.data, email=form.email.data, password=hashed)
        db.session.add(customer)
        db.session.commit()

        return redirect(url_for('customers.loginpage'))

    return render_template('customers/register.html', title='Registration Page', form=form)


@customers.route("/loginpage", methods=['GET', 'POST'])
def loginpage():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        customer = Customer.query.filter_by(username=form.username.data).first()

        if customer is not None and bcrypt.check_password_hash(customer.password, form.password.data):
            login_user(customer)
            flash(f'Welcome {form.username.data} You are logged-in now', 'success')
            return redirect(url_for('customers.account'))
        else:
            flash('Wrong Username/Password please try again', 'danger')

    return render_template('customers/login.html', title='Customer Login Page', form=form)


@customers.route("/logout")
def logout():
    username = current_user.username
    logout_user()
    current_app.logger.info('%s logged out successfully', username)
    return redirect(url_for('main.home'))


@customers.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateForm()

    if form.validate_on_submit():
        current_user.username = form.username.data

        db.session.commit()

        return redirect(url_for('customers.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username

    return render_template('customers/account.html', title='Account', form=form)

shop/main/routes.py
from flask import render_template, Blueprint, request, current_app, redirect, url_for, flash, session
from shop import db, bcrypt
from shop.admin.forms import RegistrationForm, LoginForm
from shop.products.forms import OrderForm
from shop.admin.models import User
from shop.products.models import Addproduct
from flask_login import login_user
import os
import json

main = Blueprint('main', __name__)

@main.route("/admin")
def admin():
    if 'username' not in session:
        flash('Please login first', 'danger')
        return redirect(url_for('admin.login'))
    products = Addproduct.query.all()
    return render_template('admin/index.html', title='Admin Page', products=products)

@main.route("/")
def home():
    form = OrderForm(request.form)
    # products = Addproduct.query.all()

    tshirt = Addproduct.query.filter_by(desc='T-Shirt').all()
    jewelry = Addproduct.query.filter_by(desc='Jewelry').all()
    sunglasses = Addproduct.query.filter_by(desc='Sunglasses').all()
    bands = Addproduct.query.filter_by(desc='Bands').all()

    return render_template('home.html', tshirt=tshirt, jewelry=jewelry, sunglasses=sunglasses, bands=bands, form=form)


@main.route("/about")
def about():

    return render_template('about.html', title='About')


@main.route("/csp_error_handling", methods=["POST"])
def report_handler():
    """
    Receives POST requests from the browser whenever the Content-Security-Policy
    is violated. Processes the data and logs an easy-to-read version of the message
    in your console.
    """
    report = json.loads(request.data.decode())["csp-report"]

    # current_app.logger.info(json.dumps(report, indent=2))

    violation_desc = "\nViolated directive: %s, \nBlocked: %s, \nOriginal policy: %s \n" % (
        report["violated-directive"],
        report["blocked-uri"],
        report["original-policy"]
    )

    current_app.logger.info(violation_desc)
    return redirect(url_for("main.home"))


# @main.route('/admin')
# def home():
#     if 'username' not in session:
#         flash('Please login first', 'danger')
#         return redirect(url_for('admin.login'))
#       #products = Addproduct.query.all()
#     return render_template('admin/index.html', title='Admin Page')

shop/templates/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    <div class=flashes>
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
{% endif %}
{% endwith %}

shop/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h2>About</h2>
    <p>This is a sample Ecommerce Website app that display products and allows an admin to add new products, add category, brand, and edit products. It does not allow adding products to carts, however.</p>
{% endblock %}

shop/templates/base.html
<!doctype html>
<html lang="en">
<!--  <head>-->
<!--    &lt;!&ndash; Required meta tags &ndash;&gt;-->
<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->

<!--    &lt;!&ndash; Bootstrap CSS &ndash;&gt;-->
<!--    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">-->

<!--    <title>{{title}}</title>-->
<!--  </head>-->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href={{ url_for('static', filename='css/custom.css') }}>

<!--    {% if title %}-->
<!--    <title>{{ title }}</title>-->
<!--    {% else %}-->
<!--    <title>Flask App</title>-->
<!--    {% endif %}-->
</head>
  <body>


<!--    &lt;!&ndash; Optional JavaScript &ndash;&gt;-->
<!--    &lt;!&ndash; jQuery first, then Popper.js, then Bootstrap JS &ndash;&gt;-->
<!--    <script src="{{url_for('static', filename='js/jquery-3.3.1.slim.min.js')}}"></script>-->
<!--    <script src="{{url_for('static', filename='js/popper.js/1.14.7/umd/popper.min.js')}}"></script>-->
<!--    <script src="{{url_for('static', filename='/js/bootstrap.min.js')}}"></script>-->

  <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">

            <a class="navbar-brand" href={{ url_for('main.home' )}}>JKTechExpress</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href={{ url_for('main.home') }} class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('main.about') }} class="nav-link">About</a>
                    </li>
                </ul>

                {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href=# class="nav-link">Logged in as: <b>{{ current_user.username }}</b></a>
                    </li>

                    <li class="nav-item">
                        <a href={{ url_for('customers.account' )}} class="nav-link">My Account</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('customers.logout' )}} class="nav-link">Logout</a>
                    </li>
                </ul>

                {% else %}

                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href={{ url_for('customers.loginpage' )}} class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('customers.registration' )}} class="nav-link">Register</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>

    <main class="container">
        <div class="row">
            <div class="col-md-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
  </body>
</html>

shop/templates/home.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Content -->
<div class="container">
    <div class="row">
        <!-- /.col-lg-3 -->
        <div class="col-lg-12">
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox" style="max-height: 50px">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="/static/images/other/watchwallpaper.jpg" alt="New York"
                             width="1000" height="5">
                        <div class="carousel-caption">
                            <h3>Los Angeles</h3>
                            <p>We had such a great time in LA!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/images/other/bodyspray.jpg" alt="New York" width="1000"
                             height="5">
                        <div class="carousel-caption">
                            <h3>Los Angeles</h3>
                            <p>We had such a great time in LA!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/images/other/t-shirt-wallpaper.jpg" alt="New York"
                             width="1000" height="5">
                        <div class="carousel-caption">
                            <h3>Los Angeles</h3>
                            <p>We had such a great time in LA!</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <h3><a href="/tshirt">T-Shirt</a></h3>
            <div class="row">
                {% for product in tshirt %}
                {% if product.category.name == 'T-Shirt' %}
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="card mb-4">
                        <a href="/{{product.category.name}}?view={{product.id}}">
                            <div class="card-img-top id_{{product.id}}"
                                 style="background: url('static/image/product/{{product.category}}/{{product.picture}}'); background-repeat:no-repeat; background-size: cover; height:200px;width:100% "></div>
                        </a>
                        <div class="card-body">
                            <h5><a class="card-title" href="{{product.category.name}}?view={{product.id}}">{{ product.name}}</a></h5>
                            <h4>${{product.price}}</h4>
                            <span class="text-warning"></span>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <!-- /.row -->
            <div class="border p-4 mb-4" style="height: 50px">
                <img class="w-10 h-10" src="/static/images/other/shirt.png" alt="New York">
            </div>
            <h3><a href="/bands">Bands</a></h3>
            <div class="row">
                {% for product in bands %}
                {% if product.category.name == 'Bands' %}
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="card mb-4">
                        <a href="/{{product.category.name}}?view={{product.id}}">
                            <div class="card-img-top"
                                 style="background: url('static/image/product/{{product.category}}/{{product.picture}}'); background-repeat:no-repeat; background-size: cover; height:200px;width:100% "></div>
                        </a>
                        <div class="card-body">
                            <h5><a class="card-title" id="" href="/{{product.category.name}}?view={{product.id}}">{{ product.name}}</a></h5>
                            <h4>${{product.price}}</h4>
                            <span class="text-warning"></span>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <!-- /.row -->
            <div class="border p-4 mb-4" style="height: 50px">
                <img class="w-0 h-0" src="/static/images/other/bands.jpg" alt="New York">
            </div>
            <h3><a href="/sunglasses">Sunglasses</a></h3>
            <div class="row">
                {% for product in sunglasses %}
                {% if product.category.name == 'Sunglasses' %}
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="card mb-4">
                        <a href="/{{product.category.name}}?view={{product.id}}">
                            <div class="card-img-top"
                                 style="background: url('static/image/product/{{product.category}}/{{product.picture}}'); background-repeat:no-repeat; background-size: cover; height:200px;width:100% "></div>
                        </a>
                        <div class="card-body">
                            <h5><a class="card-title" href="/{{product.category.name}}?view={{product.id}}">{{ product.name}}</a></h5>
                            <h4>${{product.price}}</h4>
                            <span class="text-warning"></span>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <div class="border p-4 mb-4" style="height: 350px">
                <img class="w-100 h-100" src="/static/images/other/sunglasses.jpg" alt="New York">
            </div>
            <h3><a href="/jewelry">Jewelry</a></h3>
            <div class="row">
                {% for product in jewelry %}
                {% if product.category.name == 'Jewelry' %}
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="card mb-4">
                        <a href="/{{product.category.name}}?view={{product.id}}">
                            <div class="card-img-top"
                                 style="background: url('static/image/product/{{product.category}}/{{product.picture}}'); background-repeat:no-repeat; background-size: cover; height:200px;width:100% "></div>
                        </a>
                        <div class="card-body">
                            <h5><a class="card-title" href="/{{product.category.name}}?view={{product.id}}">{{ product.name}}</a></h5>
                            <h4>${{product.price}}</h4>
                            <span class="text-warning"></span>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <div class="border p-1 mb-1" style="height: 50px">
                <img class="w-100 h-100" src="/static/images/other/jewelry.jpg" alt="New York">
            </div>

        </div>
        <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
{% endblock %}